# site settings
title: GAME>PLAY 2020
subtitle: Exeter > Fri 3rd - Sun 5th July 2020
subtitle2: Exeter > Fri 3rd - Sun 5th July 2020
email: gameplay@techexeter.uk
description: Exeter's biggest gaming festival 3rd - 5th July alongisde Exeter Festival
meta-description: Back for 2020, this 3 day gaming festival is programmed alongside Exeter Festival
# baseurl: / # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
google_analytics: UA-77113113-5

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url: https://instagram.com/techexeter
linkedin_url: 
pinterest_url:
slack_url: https://techexeter.uk/slack/
twitter_url: https://twitter.com/techexeter
map_url: https://gameplay.techexeter.uk/map/index.html

# build settings
markdown: kramdown

sass:
  style: compressed
